### ISSUE TITLE
Make the 'Teams' Nav link into a drop down to access other teams

### ISSUE THREAD

**Issue by srinidhibhat45** [srinidhibhat45/sushiksha-first-contributions#110]
Make the 'Teams' Nav link on the navbar into a dropdown so that all other teams can easily be accessed without having to go to the homepage again and again.

**Comment by theprojectcode** [comment]
Hey there, can I work on this?

**Comment by theprojectcode** [comment]
@srinidhibhat45

**Comment by theprojectcode** [comment]
Also, How do I get access to the slack?

**Comment by srinidhibhat45** [comment]
@theprojectcode slack is restricted to members and scholars of World Konkani Center only, sorry

**Comment by theprojectcode** [comment]
Got it! No worries, I'll just reach out on here if I have any questions. Thanks! @srinidhibhat45

**Comment by srinidhibhat45** [comment]
yes!

**Comment by theprojectcode** [comment]
Quick question, in the name area, I see that there are a few open spots to put my name, etc. in on the root "open.js" folder. Do I just choose any open space or the first one that is open? @srinidhibhat45

**Comment by srinidhibhat45** [comment]
@theprojectcode sorry, but the name cards are only for people who are in slack and part of the organization. Infact the whole repo was a tutorial repo for them and we aren't accepting cards from the public. We are accepting contributions to the website as a whole, so feel free to contribute to that

**Comment by theprojectcode** [comment]
Oh, ok. Thanks for letting me know. I thought it was a part of the steps to contribute. So I should just contribute to the issue that I was assigned to, correct?

**Comment by srinidhibhat45** [comment]
Yes!

**Comment by theprojectcode** [comment]
<img width="626" alt="Screen Shot 2021-10-13 at 8 08 11 AM" src="https://user-images.githubusercontent.com/88997637/137141991-f8f7c577-d2d3-4009-8246-26c8cce99f64.png">

I think I need a little help with my code - am I on the right path of making the right dropdown? @srinidhibhat45 for some reason I can't get the hover effect to work.
