### ISSUE TITLE
Add twitter card for the website

### ISSUE THREAD

**Issue by srinidhibhat45** [srinidhibhat45/sushiksha-first-contributions#52]
Add a Twitter card to the website. Look up about Twitter cards and add it in to the website and we'll merge your PR!

**Comment by srinidhibhat45** [comment]
Sure. @swaraj-ssk

**Comment by akshitarora921** [comment]
Hi @srinidhibhat45 , can I work on this too?

**Comment by srinidhibhat45** [comment]
Sure @akshitarora921

**Comment by akshitarora921** [comment]
Please correct me If I am wrong.
Do we want the Twitter tag to be like this?
![image](https://user-images.githubusercontent.com/11087313/135808142-169df542-e46f-437b-840c-aa21bb57bfd8.png)

**Comment by srinidhibhat45** [comment]
@akshitarora921 I asked for twitter cards. Please look that up. Its just 5 lines of code you have to place in the index.html, that's all

**Comment by akshitarora921** [comment]
@srinidhibhat45 I still didn't get you. Can we talk on any platform like discord or LinkedIn? Line of code in not an Issue ✌🏼

**Comment by srinidhibhat45** [comment]
@akshitarora921 please look up what Twitter cards are. They go into the head of an index file.

**Comment by srinidhibhat45** [comment]
@akshitarora921 @swaraj-ssk take a look here: https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started

**Comment by mitalsapkale01** [comment]
> Sure @akshitarora921

Hello, I think I can make it.... Can I contribute to o??

**Comment by akshitarora921** [comment]
Hi @mitalsapkale01, Let me give It a try, If I am not able to do it, I will tell you.
