### ISSUE TITLE
Make the navigation bar responsive for mobile devices

### ISSUE THREAD

**Issue by RishabhNaik** [srinidhibhat45/sushiksha-first-contributions#57]
In the Navbar, the links are not visible on mobile device

**Comment by Priyanshi-Raj** [comment]
I will like to contribute to this issue . Please assign me this to resolve.

**Comment by Anand911** [comment]
I have fixed the issue!!
Just Check this preview-https://anand911.github.io/sushiksha-first-contributions/index.html

**Comment by srinidhibhat45** [comment]
Fixed by @Anand911, Thank you! Closing this!
