### ISSUE TITLE
IMAGE NOT PROPERLY UPLOADED TO imgbb

### ISSUE THREAD

**Issue by Anand911** [srinidhibhat45/sushiksha-first-contributions#73]
![ISSUE1](https://user-images.githubusercontent.com/69910165/135757254-1e88f490-7562-43a9-9ee8-02136734235e.png)
@AJ-221  please look after if you have provided the same link !!

**Comment by srinidhibhat45** [comment]
resolved by him. hance closing this. Thank you!
